FROM ruby:2.3.1
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

# Install & cache gems
COPY ./Gemfile /tmp/Gemfile
COPY ./Gemfile.lock /tmp/Gemfile.lock
WORKDIR /tmp
RUN bundle install

# Add base code & node modules to app
ENV app /var/app
RUN mkdir -p $app
WORKDIR $app
ADD . $app